### ISSUE TITLE
misc TODO

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#121]
- [ ] # xxx: fix this pre-existing bug causing `SuccessX` error messages to lie

**Comment by timotheecour** [comment]
- [ ] Merging, but this needs a changelog entry and needs to be documented well.
https://github.com/nim-lang/Nim/pull/13926#issuecomment-618289112
CT sizeof(+friends) for {.importc, completeStruct.} types, enable ABI static checks

**Comment by timotheecour** [comment]
revive [[TODO] unittest: add optional msg to check, require by timotheecour · Pull Request #10558 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/10558)

eg use case: see https://github.com/nim-lang/Nim/pull/14102/files, see this comment for justification: https://github.com/nim-lang/Nim/pull/14102#discussion_r414332876

**Comment by timotheecour** [comment]
mv changelog, see https://github.com/nim-lang/Nim/pull/14098#issuecomment-619028912

**Comment by timotheecour** [comment]
- [x]  [nimvm: CritBitTree does not work: "limited VM support for 'addr'" · Issue #14339 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/14339)

**Comment by timotheecour** [comment]
- [x] repr shd use addQuoted, see [Small improvements for string and char repr with gc:arc by Clyybber · Pull Request #14400 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/14400)

Edited:
They are already quoted https://github.com/nim-lang/Nim/pull/14992/files

**Comment by timotheecour** [comment]
redo profiling after [specialize genericReset by Araq · Pull Request #14398 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/14398)

**Comment by timotheecour** [comment]
check whether NRVO suppression impacts performance [fixes #14126 [backport:1.2] by Araq · Pull Request #14390 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/14390)

**Comment by timotheecour** [comment]
do TODO from [fix #14404 foldr had the classic multiple evaluation bug by timotheecour · Pull Request #14413 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/14413)

**Comment by timotheecour** [comment]
TODO leftover from [no more code duplication bw liMessage and rawMessage + several bug fixes by timotheecour · Pull Request #14415 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/14415)
> I encountered other bugs while fixing this but best to keep this one as mostly refactoring, next one will fix bugs I've encountered (at least they'll only need to be fixed in 1 place)

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/16151/commits/70c289c46121a5182a34261177baffb8909584d6
testament/testament.nim


revert formatting change Expected: {..} Gotten{..} from this PR

```nim
    else:
      maybeStyledEcho fgYellow, "Expected:"
      maybeStyledEcho styleBright, "{", expected, "}\n"
      maybeStyledEcho fgYellow, "Gotten:"
      maybeStyledEcho styleBright, "{", given, "}\n"


```

**Comment by timotheecour** [comment]
document gotcha
https://github.com/nim-lang/Nim/pull/16182#issuecomment-735646532
> indeed. also noticed in https://github.com/nim-lang/Nim/pull/13448. It's so bad that `newSeqOfCap` should come with a performance warning in its doc comment explaining the `newSeqOfCap(n) + seq.add(elem)` anti-pattern. This isn't specific to nim.

**Comment by juancarlospaco** [comment]
- https://github.com/marketplace/actions/todo-to-issue
