### ISSUE TITLE
misc runnableExamples

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#217]
- [x] * [[docgen] proc doc comments silently omitted after 1st runnableExamples · Issue #9227 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/9227)
- [x] * [Docs shouldn't collapse pragmas inside runnableExamples/code blocks · Issue #14174 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/14174)
- [x] * [runnableExamples should preserve source code doc comments, strings, and (maybe) formatting · Issue #8871 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/8871)

**Comment by timotheecour** [comment]
- [ ] runnableExamples forwarding to nim playground

## links
* use this [provide a JSON API · Issue #18 · PMunch/nim-playground-frontend](https://github.com/PMunch/nim-playground-frontend/issues/18)

* https://github.com/nim-lang/nimbot/blob/98cc031a27ea89947daa7f0bb536bcf86462941f/src/nimbot.nim#L98

```nim
if msg.startsWith("!eval "):
        let code = msg[6 .. ^1]
        let evalResult = await evalCode(code)
```

##
 nim r -d:ssl $nim_D/nimbot/src/playground.nim

**Comment by PMunch** [comment]
The way the playground uses this (it communicates over a JSON REST API with the back-end): https://github.com/PMunch/nim-playground-frontend/blob/master/frontend.nim#L111-L112

You can select the Nim version to run, the compilation target (currently C and C++ only), and output format HTML/Ansi/AnsiParsed/Raw. HTML is with style tags to colour the output, Ansi is what the compiler outputs to the terminal, AnsiParsed is essentially the output of https://github.com/PMunch/ansiparse, and Raw is all styling stripped away.
