### ISSUE TITLE
RFC: better support for nodejs

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#342]
- [x] [js -d:nodejs now supports osenv: `getEnv`, `putEnv`, `envPairs`, `delEnv`, `existsEnv` (v2) by timotheecour · Pull Request #15826 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/15826)
- [ ] [os module nodejs support by bung87 · Pull Request #14519 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/14519)
- [ ] [pathutils_nodejs_support by bung87 · Pull Request #14512 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/14512)
- [ ] [fix #13469: defined(posix) (etc) now works with nodejs; enable os.getCurrentDir, isAbsolute + other fixes by timotheecour · Pull Request #14543 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/14543)
- [ ] etc: see other nodejs PR's

## forum
- [ ] [Sublime Text user experience - Nim forum](https://forum.nim-lang.org/t/7014#44124)
- [ ] [Any attempts at implementing filestream and std lib friends on NodeJs? - Nim forum](https://forum.nim-lang.org/t/6900)
