### ISSUE TITLE
misc high priority

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#377]
* https://github.com/timotheecour/Nim/labels/high%20priority

* [transform `static: stmt` and `const foo = expr` into immediately invoked lambas => fixes many bugs · Issue #276 · nim-lang/RFCs](https://github.com/nim-lang/RFCs/issues/276)

**Comment by timotheecour** [comment]
- [ ] revive https://github.com/nim-lang/Nim/pull/12076 resolveSymbol / overloadExists

**Comment by timotheecour** [comment]
- [ ] finish execution trace PR [execution traces (eg for code coverage, debugging, introspection) by timotheecour · Pull Request #15827 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/15827)

**Comment by timotheecour** [comment]
- [ ] nim-dustmite [TITLE: [TODO] nim-dustmite source code minimization tool for automated bug reduction · Issue #8276 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/8276)

**Comment by timotheecour** [comment]
- [ ] [  TITLE: const should work with ref types · Issue #271 · nim-lang/RFCs](https://github.com/nim-lang/RFCs/issues/271)

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/RFCs/issues/291 [RFC: `--path:prefix:path` to resolve `import prefix/suffix` · Issue #291 · nim-lang/RFCs](https://github.com/nim-lang/RFCs/issues/291)

**Comment by timotheecour** [comment]
- [ ] `const CVAR {.importc.}: int` (proposal 5 in https://github.com/nim-lang/RFCs/issues/205)

**Comment by timotheecour** [comment]
- [ ] [Terms TITLE: syntax request: `from std/[foo1,foo2] import nil` ; `from "." / [foo1,foo2] import bar1, bar2, bar3` · Issue #76 · nim-lang/RFCs](https://github.com/nim-lang/RFCs/issues/76)

**Comment by timotheecour** [comment]
- [ ] [add filewalks by timotheecour · Pull Request #32 · nim-lang/fusion](https://github.com/nim-lang/fusion/pull/32)

**Comment by timotheecour** [comment]
- [ ] revive [[TODO] new `macros.genAst`: sidesteps issues with `quote do` by timotheecour · Pull Request #11722 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/11722)
and double check [Fix macros.quote custom op symbol interpolation. by quantimnot · Pull Request #17256 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/17256/files)

**Comment by timotheecour** [comment]
- [ ] [simpler doc links: `getFilePermissions <#getFilePermissions,string>`_ => [getFilePermissions` · Issue #125 · nim-lang/RFCs](https://github.com/nim-lang/RFCs/issues/125)
