### ISSUE TITLE
misc builtin set

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#437]
refs: https://forum.nim-lang.org/t/7220#45668

- [ ] `pop` could be added to `std/setutils` (refs https://github.com/nim-lang/Nim/pull/16276),

as i argued here https://github.com/nim-lang/Nim/pull/16276#discussion_r537186214 having a dedicated sets module instead of system allows growing it without bloating the rest.

it should use `__builtin_clz` or similar

**Comment by timotheecour** [comment]
refs: https://forum.nim-lang.org/t/7220#45668


> on the topic of bit set iteration note that it's currently very inefficient, because it checks every element instead of using count leading/trailing zeroes.

- [ ] we should use builtins for platforms that support it, with a fallback for other platforms, via `__builtin_clz` + friends (first non zero bit starting from msb).

bitops.nim could import/re-export whatever's needed for builtin sets to avoid cyclic import issues and keep things DRY, possibly via some `import std/private/bitopsutils`

**Comment by timotheecour** [comment]
- [ ] improve errmsg for `set[int]` or similar

refs https://github.com/nim-lang/Nim/pull/16276#discussion_r537239913

**Comment by timotheecour** [comment]
fix conversion between sets

- [ ] [Wrong C code generated on operations on sets · Issue #16269 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/16269)

- [ ] [Codegen error when operating on sets of a type and of a range of the same type · Issue #15435 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/15435)

- [ ] [C Error on invalid uint -> set cast · Issue #3540 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/3540)

- [ ] [Codegen error when converting from set of range of integer to set of integer · Issue #16273 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/16273)

- [ ] [Wrong result on operations on sets of different types · Issue #16270 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/16270)

- [ ] [Sets: dont assume uint16 like (0 to 2^16 minus 1) as default type. · Issue #298 · nim-lang/RFCs](https://github.com/nim-lang/RFCs/issues/298)
