### ISSUE TITLE
misc cleanups

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#64]
- [ ] remove {.importc.} for js types
https://github.com/nim-lang/Nim/pull/13483#discussion_r391452475

**Comment by timotheecour** [comment]
- [ ] compiler/extccomp.nim should use json API instead of manually writing json (eg source of bugs like https://github.com/nim-lang/Nim/issues/13633, and less readable etc)

**Comment by timotheecour** [comment]
- [ ] make `exportc` imply Used for modules, see https://github.com/nim-lang/Nim/pull/13550#discussion_r392046929

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/13658#issuecomment-600002389
=> use nim program tools/nimgdb.nim `exec` or portable version of it

**Comment by timotheecour** [comment]
- [x] => https://github.com/timotheecour/Nim/issues/389

**Comment by timotheecour** [comment]
<del> deprecate isNil <del>

see also https://github.com/timotheecour/D_vs_nim/pull/36#issuecomment-610412525

Edited:
`nil == something` doesn't work with C or JS backend sometime.

**Comment by timotheecour** [comment]
- [ ] importcpp > importjs for js

**Comment by timotheecour** [comment]
- [ ] replace 
```
## some ``foo``
=>
## some `foo`
```
everywhere in nim files since it's simpler and compat w markdown

**Comment by timotheecour** [comment]
- [ ] cleanup $nim_prs_D/tests/vm/tvmops.nim
```
template forceConst(a: untyped): untyped =
  ## Force evaluation at CT, useful for example here:
  ## `callFoo(forceConst(getBar1()), getBar2())`
  ## instead of:
  ##  block:
  ##    const a = getBar1()
  ##    `callFoo(a, getBar2())`
  const ret = a
  ret
```
=> a.static

**Comment by timotheecour** [comment]
- [x] add to NEP https://nim-lang.org/docs/nep1.html
it's subjectVerb, not verbSubject, eg: deprecate existsFile for fileExists

=> https://github.com/nim-lang/Nim/pull/14732

**Comment by timotheecour** [comment]
- [x] => https://github.com/timotheecour/Nim/issues/389

**Comment by timotheecour** [comment]
- [ ] proc paramStr*(i: int): TaintedString = raise newException(OSError, "paramStr is not implemented on Genode")
=> this should be a different kind of Exception, maybe doAssert false

**Comment by timotheecour** [comment]
- [x] (=> https://github.com/timotheecour/Nim/issues/64#issuecomment-625159276))

**Comment by timotheecour** [comment]
- [x] remove all absolute html links and replace with relative links eg:
```
<https://nim-lang.org/docs/lib.html#pure-libraries-modules-for-js-backend>`_
```

**Comment by timotheecour** [comment]
- [ ] add test case for https://github.com/nim-lang/Nim/issues/11788
(just the part about:
> this is related to #11783 but seems different, as the bug in #11783 was only present when both appended and appendee were uninitialized, which isn't the case here.


var ret = "foo1"
ret.add fun()
)

**Comment by timotheecour** [comment]
can we get rid of tyOpt?

**Comment by timotheecour** [comment]
- [x] remove tyOpt
[is `tyOpt` still used? - Nim forum](https://forum.nim-lang.org/t/6299)
=> replace w tyAlias from alias PR


https://github.com/nim-lang/Nim/issues/14066#issuecomment-619824758
```
By the way, what is the tyOpt type that can be found next to seq in the code?
It is a builtin "opt[T]" type, it's dead code.
```

**Comment by timotheecour** [comment]
- [ ] turn all `code-block` (which aren't being compiled/run!) into `runnableExamples` now that most runnableExample issues have been fixed (including multiple runnableExamples at module scope).

eg of big offender:
lib/system.nim 87
lib/pure/strutils.nim 36
lib/pure/math.nim 31

total:
```
as of v1.4.0: 568
as of devel 52cf7280019c943dd7df33d0dd693931e6a116ee: 500
```
so it's going down...
(using rg code-block: -t nim  | wc -l:  500)

/cc @konsumlamm thanks for your help on this with your cleanup PR's!

**Comment by timotheecour** [comment]
- [ ] cleanup these:
`let message = "$1($2, $3) $4: $5" % [filename, $line, $col, $mc, a]` (rst.nim)
to use `toLocation`

**Comment by timotheecour** [comment]
remove entries marked `deadcode`

**Comment by timotheecour** [comment]
- [x] tests should use separate files, not isMainModule, see why here
> move test to tests/stdlib/tsequtils.nim like most modules; rationale:

https://github.com/nim-lang/Nim/pull/14413#issue-421116337

**Comment by timotheecour** [comment]
- [x] doc2 => doc 
=> https://github.com/nim-lang/Nim/pull/15683

**Comment by timotheecour** [comment]
- [ ] best practice: give warning when an iterator has multiple yield statements

$nim_prs_D/doc/contributing.rst
eg: in `nimbleSubs`

mentioned in https://nim-lang.github.io/Nim/manual.html#iterators-and-the-for-statement-first-class-iterators but hard to see

Caution: the body of a for loop over an inline iterator is inlined into each yield statement appearing in the iterator code, so ideally the code should be refactored to contain a single yield when possible to avoid code bloat.

**Comment by timotheecour** [comment]
## deadcode
- [ ] sfIsSelf
- [ ] skConditional
- [ ] remove entries marked deadcode

**Comment by timotheecour** [comment]
- [ ] compiler/options.nim removeTrailingDirSep
=>
let nimblePath = normalizePathEnd(conf.nimblePaths[i].string.byLent)


with:
```
##[
unstable API, internal use only for now.
candidate for merging in std/decls
]##

proc byLent*[T](a: var T): lent T =
  ## caveat: see https://github.com/nim-lang/Nim/issues/14557
  ## use case: convert a var to a lent to help with overload resolution, see
  ## https://github.com/timotheecour/Nim/issues/287
  a
  
```

**Comment by timotheecour** [comment]
skConditional deadcode

**Comment by timotheecour** [comment]
factor vmconv.elementType with typetraits.elementType

**Comment by timotheecour** [comment]
- [x] testament:

targets: "c c++ js"
=>
targets: "c cpp js"

(only a few c++, most are cpp)

=> https://github.com/nim-lang/Nim/pull/15961

**Comment by timotheecour** [comment]
- [ ] use
include "$nim/tests/stdlib/tdecls.nim"
instead of relative paths starting with `..`
eg

```
tests/stdlib/trst.nim:9:1:import ../../lib/packages/docutils/rstgen
tests/stdlib/trst.nim:10:1:import ../../lib/packages/docutils/rst
tests/stdlib/trstgen.nim:7:1:import ../../lib/packages/docutils/rstgen
tests/stdlib/trstgen.nim:8:1:import ../../lib/packages/docutils/rst
tests/stdlib/tstrutils2.nim:1:1:import "$lib/.." / compiler/strutils2
tools/grammar_nanny.nim:6:1:import ".." / compiler / [
tools/kochdocs.nim:5:1:import "../compiler/nimpaths"
tools/nimfind.nim:33:1:import "../compiler" / [options, commands, modules, sem,
tools/winrelease.nim:7:1:import "../koch"

```

note:

might require: [`nim --prefix:PATH` to set the prefix path (might be more useful than --lib:lib) · Issue #365 · timotheecour/Nim](https://github.com/timotheecour/Nim/issues/365)

**Comment by timotheecour** [comment]
- [ ] testament: get rid of isSuccess, use exit code
[in TITLE: Testament failure with reNimcCrash - Nim forum](https://forum.nim-lang.org/t/6999)

**Comment by timotheecour** [comment]
- [ ] change `assert` to `doAssert` in tests

EDIT: see https://github.com/nim-lang/Nim/pull/16486#issuecomment-751928805 for remaining assert's to change

**Comment by timotheecour** [comment]
- [ ] `Fixed “backticks : Using reserved keywords as identifiers is not documented” (#15806)` repeated 4 times in https://nim-lang.org/blog/2020/12/01/version-142-released.html

```
Fixed “lent gives wrong results with -d:release” (#14578)
Fixed “backticks : Using reserved keywords as identifiers is not documented” (#15806)
Fixed “backticks : Using reserved keywords as identifiers is not documented” (#15806)
Fixed “backticks : Using reserved keywords as identifiers is not documented” (#15806)
Fixed “backticks : Using reserved keywords as identifiers is not documented” (#15806)
Fixed “Program SIGSEGV when using ‘–gc:orc’” (#15753)
```

**Comment by timotheecour** [comment]
- [ ] testament: get rid of redundant:
```
action: run
```

and:
```
  exitcode: 0
```

**Comment by timotheecour** [comment]
- [ ] simplify wrappers eg https://github.com/nim-lang/Nim/pull/16320#discussion_r542191268

use this:
```nim
{.pragma: lcrypto, cdecl, dynlib: DLLUtilName, importc.}
```
and then use this pragma everywhere relevant in this file, eg:
```nim
proc BIO_read*(b: BIO, data: cstring, length: cint): cint {.lcrypto.}
```
instead of:
```nim
proc BIO_read*(b: BIO, data: cstring, length: cint): cint{.cdecl,
      dynlib: DLLUtilName, importc.}
```

## note:
this is preferable to {.push.} {.pop.} as it's more explicit (less "hidden state")

**Comment by timotheecour** [comment]
- [ ] replace "proc `==~`" by the new `math.almostEqual`:
tmath.nim:
```nim
    proc `==~`(x, y: float): bool = (abs(x-y) < 1e-9)
```

tcomplex.nim:
```nim
proc `=~`[T](x, y: Complex[T]): bool =
  result = abs(x.re-y.re) < 1e-6 and abs(x.im-y.im) < 1e-6

proc `=~`[T](x: Complex[T]; y: T): bool =
  result = abs(x.re-y) < 1e-6 and abs(x.im) < 1e-6
```

**Comment by xflywind** [comment]
It doesn't look good to me though,
```nim
proc `==~`(x, y: float): bool = almostEqual(x, y, 100)
```

**Comment by timotheecour** [comment]
- [x] pragma before generic parameter list 
https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-importcpp-pragma
example would give: `Warning: pragma before generic parameter list is deprecated [Deprecated]`

```nim
type
  StdMap {.importcpp: "std::map", header: "<map>".} [K, V] = object
=>
type
  StdMap [K, V] {.importcpp: "std::map", header: "<map>".} = object
```
https://github.com/nim-lang/Nim/pull/16497

**Comment by timotheecour** [comment]
- [ ] add `--styleCheck:error` to tests/config.nims + whatever nim doc runs in CI and whitelist things where this doesn't work yet

**Comment by timotheecour** [comment]
- [ ] add `--warningAsError` to tests/config.nims + whatever `nim doc` runs in CI (would be made easier with https://github.com/nim-lang/Nim/pull/14068)

**Comment by timotheecour** [comment]
- [ ] code-block:: Nim in $nim_prs_D/lib/pure/htmlparser.nim is potentially dangerous
(involves: `writeFile("output.html", $html)`)
and anyways should be replaced by a (non-dangerous) runnableExamples

**Comment by timotheecour** [comment]
- [ ] fix style for lib/js/jsffi.nim and /lib/std/private/*.nim

https://github.com/nim-lang/fusion/pull/64#issuecomment-753683927
> because theres stuff with broken style on Nim main repo on /lib/js/jsffi.nim and /lib/std/private/*.nim.

**Comment by timotheecour** [comment]
- [x] fix things like: `when not defined(js) and not defined(nimdoc)` which are often wrong
and replace with: `when not defined(js)`

refs: https://github.com/nim-lang/fusion/pull/57#discussion_r551087943 and `nim doc -b:js`

=> fixed in https://github.com/nim-lang/Nim/pull/16579

**Comment by timotheecour** [comment]
move `-d:testing` to tests/config.nims so it applies to all tests even ones run via `exec nim` inside tests

**Comment by timotheecour** [comment]
- [ ] change all these:
```nim
when not defined(js):
  {.error: "Module jsFFI is designed to be used with the JavaScript backend.".}
```
into these:
```nim
when not defined(js):
  {.fatal: "Module jsFFI is designed to be used with the JavaScript backend.".}
```

rationale: `nim check` (or `nim r --errormax:10`) will otherwise show tons of (irrelevant) errors otherwise (try with: `nim check lib/js/jsre.nim`)

In these case, early abort is correct.

## note
ditto in similar other cases, eg with cpp instead of js etc

**Comment by timotheecour** [comment]
- [ ] refs https://github.com/nim-lang/Nim/pull/16577#discussion_r551367191
document `-d:nimMegatest`

**Comment by ringabout** [comment]
not now
- [ ] use `math.isNaN`
```
  if (result.n[0].kind in {nkFloatLit..nkFloat64Lit} and classify(result.n[0].floatVal) == fcNan) or
      (result.n[1].kind in {nkFloatLit..nkFloat64Lit} and classify(result.n[1].floatVal) == fcNan):
    localError(c.config, n.info, "NaN is not a valid start or end for a range")
```

**Comment by timotheecour** [comment]
- [ ] cleanup:
lib/pure/asynchttpserver.nim
```nim
      var (address, client) = await server.socket.acceptAddr()
      asyncCheck processClient(server, client, address, callback)
```
=>
```nim
      await server.acceptRequest(callback)
```

**Comment by timotheecour** [comment]
- [ ] address review comments in https://github.com/nim-lang/Nim/pull/16660 that was merged

**Comment by timotheecour** [comment]
- [x] add back at least this doc change `## and expect a reasonable result - use the `isNaN` or `classify` procedure` from closed PR  https://github.com/nim-lang/Nim/pull/16627

**Comment by timotheecour** [comment]
- [x] csize=>csize_t
eg: posix.nim(885, 29) Warning: use `csize_t` instead; csize is deprecated [Deprecated]

**Comment by timotheecour** [comment]
- [ ] use `--warningAsError:UnusedImport` in several places to avoid corresponding regressions:
* in runCI during bootstrap of nim (easy)
* in tests/config.nims (harder as may need to fix tests); note: individual tests can override via `--warningAsError:UnusedImport:off`, probably
* in kochdocs.nim instead of this (harder):

```
nimArgs = "--errormax:3 --hint:Conf:off --hint:Path:off --hint:Processing:off --hint:XDeclaredButNotUsed:off --warning:UnusedImport:off -d:boot --putenv:nimversion=$#" % system.NimVersion
```

**Comment by timotheecour** [comment]
- [x] (migrated to https://github.com/timotheecour/Nim/issues/525)

**Comment by timotheecour** [comment]
- [ ] `SOURCE_DATE_EPOCH` should be removed/replaced

**Comment by timotheecour** [comment]
- [ ] move all ffi docs (and pragmas) from manual to a separate ffi_c, ffi_cpp, ffi_js rst files

refs https://github.com/nim-lang/Nim/pull/16750#issuecomment-768529881

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/16549#discussion_r550903641

> weak test, doesn't check that
hash(x) == static(hash(x)) in this branch

**Comment by timotheecour** [comment]
- [ ] 2021-02-18T07:56:46.4635833Z D:\a\1\s\lib\impure\db_sqlite.nim(184, 1) Warning: Circular dependency detected. `codeReordering` pragma may not be able to reorder some nodes properely [User]

https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/13280/logs/99
