### ISSUE TITLE
issue collections

### ISSUE THREAD

**Issue by ringabout** [timotheecour/Nim#814]
## issues from nimskull

https://github.com/nim-works/nimskull/issues/41

## JS backend
The programs below doesn't work with JS backend
- [ ] enum corner case in JS backend
```nim
type
  c_git_diff_option_t* = enum
    c_GIT_DIFF_NORMAL                          = 0 shl 0
    c_GIT_DIFF_IGNORE_BLANK_LINES              = 1 shl 31
```
Ref nim-works/nimskull#10

int is 32 bit for JS VM/backend

- [ ] construction with side effects expression in JS backend
```nim
block multi_key:
  var used = 0
  let curly = {
    "key1", "key2": (inc used; used),
    "key3": (inc used; used)
  }

  doAssert used == 3, "Expression is evaluated for each key"
  doAssert curly == [
    ("key1", 1),
    ("key2", 2),
    ("key3", 3)
  ]
```

###

- [x] Nim compiler ignore leading spaces. In contrast, `  import os` causes indentation error in Python.
```nim
   import os
block:
  echo 123
```

### Json
- [ ] ref nim-lang#1553; bring some documentation of `std/json` back
