### ISSUE TITLE
misc tracking of unresolved issues/comments

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#87]
* https://github.com/nitely/nim-regex/pull/58#issuecomment-608957914
* https://github.com/nitely/nim-regex/issues/57

**Comment by timotheecour** [comment]
* [--nimargs: eg `choosenim 1.2.0 --nimargs -d:danger -d:nimEmulateOverflowChecks` · Issue #190 · dom96/choosenim : --nimargs: eg `choosenim 1.2.0 --nimargs -d:danger -d:nimEmulateOverflowChecks` · Issue #190 · dom96/choosenim](https://github.com/dom96/choosenim/issues/190)

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/13952/files#r407126554
> this is a bug. it'll only run for nim c since that's what's in cmd.

**Comment by timotheecour** [comment]
1 branch per major.minor version
`https://github.com/nim-lang/Nim/pull/13907#issuecomment-612545166`

**Comment by timotheecour** [comment]
since debate https://github.com/nim-lang/Nim/pull/13920#issuecomment-613204716

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/7508#issuecomment-616952848

**Comment by timotheecour** [comment]
- [ ] getSelection
https://github.com/nim-lang/Nim/pull/13632#discussion_r401320921

this causes RT error Uncaught TypeError: a_2990031.$ is not a function

the bug is that it's inside a importcpp section so gets interpreted as such

**Comment by timotheecour** [comment]
- [ ] not nil documentation lying: https://github.com/nim-lang/Nim/pull/14027#discussion_r411059059

**Comment by timotheecour** [comment]
<FromDiscord> <Skaruts> if I do import foo except a, b and then export foo, does a and b get exported with the module?

??

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/14190#issuecomment-624489897
warningAsError:warnUnreachableElse:on

**Comment by timotheecour** [comment]
[`nim dump` is roughly 100x slower in 1.3 versus 1.2 · Issue #14179 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/14179)

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/14321#issuecomment-627354271 `importc let` tests

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/issues/14331#issuecomment-628005358

**Comment by timotheecour** [comment]
[provide a JSON API · Issue #18 · PMunch/nim-playground-frontend](https://github.com/PMunch/nim-playground-frontend/issues/18)

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/issues/14126#issuecomment-635159230

> causes significant regressions in stack usage due to RVO not being applied even in safe cases (no exceptions involved) - the proposed fix is too aggressive!

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/commit/d3b25a294858f655eef8c45d2a8b8b55261d53ac#commitcomment-39878756

getCurrentExceptionMsg and getCurrentException() are available, they're just returning default values (instead of giving CT error or the actually exception string and exception).

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/15649#issuecomment-714174524

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/15701/files#r511508506
actionRetry
> why did you remove this? this was there for a good reason, reducing spurious git clone failures which used to happen a lot before this was added

EDIT: maybe also related:
Error: unhandled exception: D:\a\1\s\tools\deps.nim(6, 12) `status == 0` git clone -q https://github.com/nim-lang/nimble.git D:\a\1\s\dist\nimble [AssertionDefect]

https://dev.azure.com/nim-lang/Nim/_build/results?buildId=9633&view=logs&jobId=8771bebc-ff97-51ac-1845-cb5b61e3bccd&j=8771bebc-ff97-51ac-1845-cb5b61e3bccd&t=74a5fa6a-7085-521f-3e7a-45825f3ff79f

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/15705#issuecomment-716104694

> can you explain the added c.freeTemp(dest) in genBinaryStmtVar, genBinaryStmt, genAsgn, nkDerefExpr etc ?

Not anymore but I did review the entire VM codegen looking for register allocator leaks. Apparently my work wasn't good enough. ;-)

**Comment by timotheecour** [comment]
https://github.com/yglukhov/nimpy/pull/177#issuecomment-716567031

**Comment by timotheecour** [comment]
[honor --declaredLocs in more places, including type mismatch errors; also show `kind` with --declaredLocs by timotheecour · Pull Request #15673 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/15673)
=> we should also honor --declaredLocs for cannot instantiate errors:

**Comment by timotheecour** [comment]
D20201030T193806 https://github.com/narimiran/Nim/commit/26816d59bac49c769e9f11570f357e855c526811#r43738252

https://github.com/nim-lang/Nim/pull/15792#commitcomment-43738252

**Comment by timotheecour** [comment]
~~https://github.com/nim-lang/Nim/issues/8821#issuecomment-720390217~~

**Comment by timotheecour** [comment]
~~https://github.com/sindresorhus/refined-github/pull/3698#issuecomment-725722505~~

**Comment by timotheecour** [comment]
~~https://github.com/Homebrew/brew/issues/9120#issuecomment-726353222
can you please re-open? I've edited OP and added brew config and brew doctor outputs~~

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/15421/files#r522703485

TODO for future PR:
this will show weird looking errors:
input ['1', '2', ',', '1', '.'] [ValueError]
instead of:
input "12,1." [ValueError]

I sent out #15951 ; when this is merged we can revisit this using add

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/15994#issuecomment-729303508
contributing.rst: multiple error msgs via nim check

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/16087#issuecomment-731635458

tests/collections/tsets.nim
instead of
tests/collections/thashsets.nim

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/16016/files#r529855465
stderr.write on all backends

**Comment by timotheecour** [comment]
fix these:
[Assignees TITLE: move tests to testament by xflywind · Pull Request #16101 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/16101)
- [ ] use include because some symbols are not exported
- [ ] disable testing random module

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/16004#issuecomment-735040519
std/sums => fusion/sums

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/16163#discussion_r532007171

improve on:

> doAssert fileExists(test), test & " test does not exist"

in testament

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/issues/16303#issuecomment-742154273
>  yes. #10841 should be revisited and #10838 should be fixed in a way than amounts to adding {.noSideEffect.}

**Comment by timotheecour** [comment]
- [ ] remove out mentions from manual_experimental.rst since nothing works
https://github.com/nim-lang/Nim/pull/16378#issuecomment-747606595

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/16385#pullrequestreview-555811149

> where does this magic h > 4 comes from? shouldn't that at least be h > 2 ?

**Comment by timotheecour** [comment]
https://github.com/nim-lang/fusion/pull/56/files#r546161354

 * I think this should be `ref object of JsRoot`
 * we also need to fix similar errors in stdlib:

```nim
lib/js/dom.nim:1213:28:  TouchList* {.importc.} = ref object of RootObj
lib/js/dom.nim:1293:26:  TimeOut* {.importc.} = ref object of RootObj
lib/js/jsconsole.nim:16:17:type Console* = ref object of RootObj
lib/js/jsffi.nim:87:15:  JsObject* = ref object of JsRoot
lib/js/jsffi.nim:89:27:  JsAssoc*[K: JsKey, V] = ref object of JsRoot
```
PR's welcome!

**Comment by ringabout** [comment]
- [ ] Add compile-time unrolled for loops 
https://github.com/nim-lang/Nim/pull/15456

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/16461#issuecomment-751443292
after that PR, code becomes slower on benchmark

> the newer code is slower.

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/16480/files#r556247845 mimesLongest

**Comment by timotheecour** [comment]
- [ ] [Transfer-Encoding:chunked tests by vabresto · Pull Request #16678 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/16678)

> For reference, I explained how to resolve this here: irclogs.nim-lang.org/13-01-2021.html#23:38:06

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/16453#issuecomment-761278816

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/16728#discussion_r558279460
> should this be arr: Float64Array or arr: var Float64Array ? I'm really not sure here since the type is ref, but really, Float64Array + friends act like seq, so var seems to make more sense here.

**Comment by timotheecour** [comment]
- [x] https://github.com/nim-lang/Nim/pull/16807/files/560ef3a44f9c8f9ae0a0212baf5ae9567ee9238e#diff-949fbeaf84606faa8c27eb4619bb6f3b263ace4efedd31c9b0c65744459bc4ae

> please (in followup PR) move this to the existing tests/stdlib/tjsonmacro.nim inside testJson which automatically tests in c, js, vm

**Comment by timotheecour** [comment]
- [ ] document semicolumn vs comma in  `fn[T; U: Ordinal]()`
refs https://github.com/nim-lang/Nim/pull/16853#discussion_r566674686

**Comment by timotheecour** [comment]
- [ ] allow distinctBase for non distinct types refs https://github.com/nim-lang/Nim/pull/16864/files#r567009043

**Comment by timotheecour** [comment]
- [ ] reenable fidget refs https://github.com/treeform/fidget/issues/133#issuecomment-769993052

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/16884/files#r567646940
does 
```nim
lineF(p, "$1 = nimCopy(null, $2, $3);$n",
               [a.rdLoc, b.res, genTypeInfo(p, y.typ)])
```
a few lines above also need to change to y.typ => x.typ?
(I don't know which one is correct)

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/16886#issuecomment-770496617
future work:
* cross reference system.cpuEndians and std/endians (help welcome @konsumlamm)
* add tests/stdlib/tendians
* add tests for cpuEndian in c/js/vm
* add `getEndian` in `std/endians` as shown in https://github.com/nim-lang/Nim/pull/16886#issuecomment-770388590 or https://github.com/timotheecour/Nim/issues/515

**Comment by timotheecour** [comment]
- [ ] remove `appendMoved` refs https://github.com/nim-lang/Nim/pull/16536#discussion_r561428854

**Comment by timotheecour** [comment]
- [x] nep1: decide on `1..3` vs `1 .. 3`, refs https://github.com/nim-lang/Nim/pull/16981#discussion_r573199503

**Comment by timotheecour** [comment]
- [ ] use blacklists, not whitelists
refs https://github.com/nim-lang/Nim/pull/16878#issuecomment-777957760
tests/test_nimscript.nims 
tests/effects/tstrict_funcs_imports.nim
etc

**Comment by timotheecour** [comment]
- [ ] js foreign exception name

https://github.com/nim-lang/Nim/pull/16998#discussion_r575642045

**Comment by SebTardif** [comment]
> ~[Homebrew/brew#9120 (comment)](https://github.com/Homebrew/brew/issues/9120#issuecomment-726353222) can you please re-open? I've edited OP and added brew config and brew doctor outputs~

I don't understands this ticket 87 and why 9120 is closed because I do see the error: "Error: Too many open files" every month on WSL when running "brew upgrade". Should I open a new issue for "Error: Too many open files"?
